import type { KeyboardLayout } from "./types";

export const azertyFr: KeyboardLayout = {
  id: "azerty-fr",
  name: "AZERTY (FR)",
  rows: [
    // Row 1: Number row — unshifted produces symbols, Shift produces digits
    [
      { code: "Escape", label: "Esc", w: 1.5 },
      { code: "Backquote", label: "\u00b2" },
      { code: "Digit1", label: "&" },
      { code: "Digit2", label: "\u00e9" },
      { code: "Digit3", label: '"' },
      { code: "Digit4", label: "'" },
      { code: "Digit5", label: "(" },
      { code: "Digit6", label: "-" },
      { code: "Digit7", label: "\u00e8" },
      { code: "Digit8", label: "_" },
      { code: "Digit9", label: "\u00e7" },
      { code: "Digit0", label: "\u00e0" },
      { code: "Minus", label: ")" },
      { code: "Equal", label: "=" },
      { code: "Backspace", label: "Backspace", w: 2 },
    ],
    // Row 2: Top row
    [
      { code: "Tab", label: "Tab", w: 1.5 },
      { code: "KeyQ", label: "a" },
      { code: "KeyW", label: "z" },
      { code: "KeyE", label: "e" },
      { code: "KeyR", label: "r" },
      { code: "KeyT", label: "t" },
      { code: "KeyY", label: "y" },
      { code: "KeyU", label: "u" },
      { code: "KeyI", label: "i" },
      { code: "KeyO", label: "o" },
      { code: "KeyP", label: "p" },
      { code: "BracketLeft", label: "^" },
      { code: "BracketRight", label: "$" },
      { code: "Backslash", label: "*" },
    ],
    // Row 3: Home row
    [
      { code: "CapsLock", label: "CapsLock", w: 1.75 },
      { code: "KeyA", label: "q" },
      { code: "KeyS", label: "s" },
      { code: "KeyD", label: "d" },
      { code: "KeyF", label: "f" },
      { code: "KeyG", label: "g" },
      { code: "KeyH", label: "h" },
      { code: "KeyJ", label: "j" },
      { code: "KeyK", label: "k" },
      { code: "KeyL", label: "l" },
      { code: "Semicolon", label: "m" },
      { code: "Quote", label: "\u00f9" },
      { code: "Enter", label: "Enter", w: 2.25 },
    ],
    // Row 4: Bottom row
    [
      { code: "ShiftLeft", label: "Shift", w: 2.25 },
      { code: "KeyZ", label: "w" },
      { code: "KeyX", label: "x" },
      { code: "KeyC", label: "c" },
      { code: "KeyV", label: "v" },
      { code: "KeyB", label: "b" },
      { code: "KeyN", label: "n" },
      { code: "KeyM", label: "," },
      { code: "Comma", label: ";" },
      { code: "Period", label: ":" },
      { code: "Slash", label: "!" },
      { code: "ShiftRight", label: "Shift", w: 2.25 },
    ],
    // Row 5: Modifier row
    [
      { code: "ControlLeft", label: "Ctrl", w: 1.25 },
      { code: "MetaLeft", label: "Meta", w: 1.25 },
      { code: "AltLeft", label: "Alt", w: 1.25 },
      { code: "Space", label: "", w: 6.25 },
      { code: "AltRight", label: "AltGr", w: 1.25 },
      { code: "MetaRight", label: "Meta", w: 1.25 },
      { code: "ControlRight", label: "Ctrl", w: 1.25 },
    ],
  ],
};
