import type { KeyboardLayout } from "./types";

export const dvorak: KeyboardLayout = {
  id: "dvorak",
  name: "Dvorak",
  rows: [
    // Row 1: Number row (same as QWERTY)
    [
      { code: "Escape", label: "Esc", w: 1.5 },
      { code: "Backquote", label: "`" },
      { code: "Digit1", label: "1" },
      { code: "Digit2", label: "2" },
      { code: "Digit3", label: "3" },
      { code: "Digit4", label: "4" },
      { code: "Digit5", label: "5" },
      { code: "Digit6", label: "6" },
      { code: "Digit7", label: "7" },
      { code: "Digit8", label: "8" },
      { code: "Digit9", label: "9" },
      { code: "Digit0", label: "0" },
      { code: "Minus", label: "[" },
      { code: "Equal", label: "]" },
      { code: "Backspace", label: "Backspace", w: 2 },
    ],
    // Row 2: Top row
    [
      { code: "Tab", label: "Tab", w: 1.5 },
      { code: "KeyQ", label: "'" },
      { code: "KeyW", label: "," },
      { code: "KeyE", label: "." },
      { code: "KeyR", label: "p" },
      { code: "KeyT", label: "y" },
      { code: "KeyY", label: "f" },
      { code: "KeyU", label: "g" },
      { code: "KeyI", label: "c" },
      { code: "KeyO", label: "r" },
      { code: "KeyP", label: "l" },
      { code: "BracketLeft", label: "/" },
      { code: "BracketRight", label: "=" },
      { code: "Backslash", label: "\\" },
    ],
    // Row 3: Home row
    [
      { code: "CapsLock", label: "CapsLock", w: 1.75 },
      { code: "KeyA", label: "a" },
      { code: "KeyS", label: "o" },
      { code: "KeyD", label: "e" },
      { code: "KeyF", label: "u" },
      { code: "KeyG", label: "i" },
      { code: "KeyH", label: "d" },
      { code: "KeyJ", label: "h" },
      { code: "KeyK", label: "t" },
      { code: "KeyL", label: "n" },
      { code: "Semicolon", label: "s" },
      { code: "Quote", label: "-" },
      { code: "Enter", label: "Enter", w: 2.25 },
    ],
    // Row 4: Bottom row
    [
      { code: "ShiftLeft", label: "Shift", w: 2.25 },
      { code: "KeyZ", label: ";" },
      { code: "KeyX", label: "q" },
      { code: "KeyC", label: "j" },
      { code: "KeyV", label: "k" },
      { code: "KeyB", label: "x" },
      { code: "KeyN", label: "b" },
      { code: "KeyM", label: "m" },
      { code: "Comma", label: "w" },
      { code: "Period", label: "v" },
      { code: "Slash", label: "z" },
      { code: "ShiftRight", label: "Shift", w: 2.25 },
    ],
    // Row 5: Modifier row (same as QWERTY)
    [
      { code: "ControlLeft", label: "Ctrl", w: 1.25 },
      { code: "MetaLeft", label: "Meta", w: 1.25 },
      { code: "AltLeft", label: "Alt", w: 1.25 },
      { code: "Space", label: "", w: 6.25 },
      { code: "AltRight", label: "Alt", w: 1.25 },
      { code: "MetaRight", label: "Meta", w: 1.25 },
      { code: "ControlRight", label: "Ctrl", w: 1.25 },
    ],
  ],
};
