import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

interface GeneratedOperator {
  name: string;
  bare_identity?: string;
  namespace_applicability?: Array<{ namespace: string; spelling: string; identity: string }>;
  parameters?: Array<{ name: string }>;
}

interface GeneratedReferenceData {
  schema_version: number;
  generated_from: string[];
  namespaces: Array<{ name: string; semantics: string }>;
  operators: GeneratedOperator[];
}

const data = JSON.parse(
  readFileSync("assets/modulisp_reference_data.json", "utf8"),
) as GeneratedReferenceData;

describe("generated operator namespace reference data", () => {
  it("records its engine sources and the closed namespace set", () => {
    expect(data.schema_version).toBe(2);
    expect(data.generated_from).toContain("src-useq/uSEQ/src/signal_engine/symbols.def");
    expect(data.namespaces.map((namespace) => namespace.name)).toEqual([
      "n", "r", "u", "b", "lfo", "blfo", "osc", "k", "raw",
    ]);
  });

  it("derives bare identity and applicability for declared operators", () => {
    const sin = data.operators.find((operator) => operator.name === "sin");
    expect(sin?.bare_identity).toBe("n/sin");
    expect(sin?.namespace_applicability?.map((cell) => cell.namespace)).toEqual([
      "n", "r", "u", "b", "lfo", "blfo", "k", "raw",
    ]);
    expect(data.operators.find((operator) => operator.name === "osc/sine")
      ?.namespace_applicability).toEqual([
      { namespace: "osc", spelling: "osc/sine", identity: "osc/sine" },
    ]);
  });

  it("contains exact phasor-last Euclid grammar and no removed names", () => {
    const euclid = data.operators.find((operator) => operator.name === "euclid");
    expect(euclid?.parameters?.map((parameter) => parameter.name)).toEqual([
      "hits", "total", "pulse-width", "rotation", "phasor",
    ]);
    expect(data.operators.map((operator) => operator.name)).not.toEqual(
      expect.arrayContaining(["usin", "ucos", "osc", "tri-osc", "sqr-osc"]),
    );
  });

  it("is generated by the asset pipeline rather than copied as a static table", () => {
    const buildScript = readFileSync("scripts/build-assets.mjs", "utf8");
    expect(buildScript).toContain("generateReferenceData()");
    expect(buildScript).not.toContain("copyFileSync(referenceDataFile.src");
  });
});
