#!/usr/bin/env bash
# Regenerates wiki/by-the-numbers.md from REAL git + wc data.
#
# Why this exists: the wiki/ tree is local-only (gitignored) and was originally
# auto-generated with hand-baked numbers that drifted from reality (file counts
# off ~2x, TODO count off ~2x, line counts and churn inflated). This generator
# computes the same facts from the repo itself so they are correct on every run
# and cite their own source. The wiki output stays gitignored; this script is
# tracked.
#
# Dependency-free: uses only git, wc, awk, grep (no tokei/cloc/node needed),
# so it runs identically locally and in CI.
#
# Usage:
#   scripts/gen-by-the-numbers.sh [output_path]
#     output_path defaults to <repo>/wiki/by-the-numbers.md
#     pass "-" to write to stdout instead.
#
# Note: no `pipefail`. These are analytics pipelines where a zero-match `grep`
# (e.g. a language bucket with no files) is an expected outcome, not an error —
# pipefail would abort the run on the first empty bucket.
set -eu

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

OUT="${1:-$ROOT/wiki/by-the-numbers.md}"
TODAY="$(date +%Y-%m-%d)"
SINCE="90 days ago"

# --- tracked TS/TSX under src/ --------------------------------------------
mapfile -t TS_FILES < <(git ls-files | grep -E '^src/.*\.tsx?$')
TS_COUNT=${#TS_FILES[@]}
TS_TEST_COUNT=$(printf '%s\n' "${TS_FILES[@]}" | grep -cE '\.test\.tsx?$' || true)
TS_SRC_COUNT=$(( TS_COUNT - TS_TEST_COUNT ))
TS_LOC=$(printf '%s\n' "${TS_FILES[@]}" | tr '\n' '\0' | xargs -0 cat 2>/dev/null | wc -l | tr -d ' ')

MJS_TEST_COUNT=$(git ls-files | grep -cE '^test/.*\.mjs$' || true)
SPEC_COUNT=$(git ls-files | grep -cE '^docs/specs/.*\.md$' || true)
CFG_COUNT=$(git ls-files | grep -E '\.(json|ya?ml)$' | wc -l | tr -d ' ')

# --- language buckets for the bar chart (whole tracked tree) --------------
bucket_loc() { git ls-files | grep -E "$1" | tr '\n' '\0' | xargs -0 cat 2>/dev/null | wc -l | tr -d ' '; }
TS_REPO_LOC=$(bucket_loc '\.tsx?$')
JS_LOC=$(bucket_loc '\.(c|m)?js$')
MD_LOC=$(bucket_loc '\.md$')
CFG_LOC=$(bucket_loc '\.(json|ya?ml)$')

CPP_LOC=0
if git -C src-useq rev-parse --git-dir >/dev/null 2>&1; then
  CPP_LOC=$( ( cd src-useq && git ls-files | grep -E '\.(c|cc|cpp|cxx|h|hpp|hxx)$' \
            | tr '\n' '\0' | xargs -0 cat 2>/dev/null | wc -l ) | tr -d ' ')
fi

YMAX=$(awk -v a="$TS_REPO_LOC" -v b="$CPP_LOC" \
  'BEGIN{ m=a; if(b>m)m=b; print int((m+9999)/10000)*10000 }')

if [ "$CPP_LOC" -eq 0 ]; then
  SUBMODULE_NOTE="> **Note:** the \`src-useq/\` firmware submodule is not checked out in this worktree, so the C/C++ bar reads 0. Run \`git submodule update --init\` and rerun to include the firmware line count."
else
  SUBMODULE_NOTE=""
fi

# --- longest TS/TSX files in src/ (top 10) --------------------------------
LONGEST=$(printf '%s\n' "${TS_FILES[@]}" | tr '\n' '\0' | xargs -0 wc -l 2>/dev/null \
  | awk '$2!="total"{print $1"\t"$2}' | sort -rn \
  | awk -F'\t' 'NR<=10{printf "| `%s` | %s |\n", $2, $1}')

# --- churn hotspots: most-touched src TS/TSX over the window (top 8) ------
CHURN=$(git log --since="$SINCE" --name-only --pretty=format: -- src \
  | grep -E '\.tsx?$' | sort | uniq -c | sort -rn \
  | awk 'NR<=8{printf "| `%s` | %s |\n", $2, $1}')

# --- TODO / FIXME / HACK in tracked src TS/TSX ----------------------------
TODO_COUNT=$(git grep -nIE 'TODO|FIXME|HACK' -- src 2>/dev/null \
  | grep -cE '^src/[^:]*\.tsx?:' || true)

# --- bot-attributed commits ------------------------------------------------
TOTAL_COMMITS=$(git rev-list --count HEAD)
BOT_COMMITS=$(git log --format='%an' | grep -cE '\[bot\]' || true)
BOT_PCT=$(awk -v b="$BOT_COMMITS" -v t="$TOTAL_COMMITS" 'BEGIN{ printf "%.0f", (t? b*100.0/t : 0) }')
if [ "$BOT_COMMITS" -eq 0 ]; then
  BOT_DESC="none"
else
  BOT_DESC="~${BOT_PCT}% of history"
fi
COMMITS_WINDOW=$(git log --since="$SINCE" --oneline | wc -l | tr -d ' ')

# --- emit ------------------------------------------------------------------
render() {
cat <<EOF
# By the numbers

*Generated by \`scripts/gen-by-the-numbers.sh\` on ${TODAY}. Do not
hand-edit — rerun the script. Counts cover git-tracked files only.*

A quantitative snapshot of the uSEQ Perform codebase: size, churn, and
complexity hotspots, computed directly from \`git\` + \`wc\`.

## Codebase size and languages

Tracked TypeScript/TSX under \`src/\` totals **${TS_LOC} lines** across
**${TS_COUNT} files**. Language distribution across the whole tracked tree
(the C/C++ figure is the \`src-useq/\` firmware submodule):

\`\`\`mermaid
xychart-beta
    title "Tracked lines of code by language"
    x-axis ["TS/TSX", "C/C++ (sub)", "JS", "Markdown", "JSON/YAML"]
    y-axis "Lines of code" 0 --> ${YMAX}
    bar [${TS_REPO_LOC}, ${CPP_LOC}, ${JS_LOC}, ${MD_LOC}, ${CFG_LOC}]
\`\`\`

${SUBMODULE_NOTE}

### File count distribution

* **Source files (TS/TSX, non-test) in \`src/\`**: ${TS_SRC_COUNT}
* **Test files (\`*.test.ts/tsx\` in \`src/\`)**: ${TS_TEST_COUNT}
* **Structural YAML/Mocha tests (\`test/**/*.mjs\`)**: ${MJS_TEST_COUNT}
* **Specification files (\`docs/specs/*.md\`)**: ${SPEC_COUNT}
* **Config/build files (JSON/YAML)**: ${CFG_COUNT}

---

## Codebase churn hotspots

Most-modified \`src/\` TS/TSX files over the last 90 days. High-churn files are
active feature frontiers or integration chokepoints:

| Path | Commits (90d) |
| --- | --- |
${CHURN}

---

## Complexity and size hotspots

Longest TS/TSX files in \`src/\` — prime candidates for modular decomposition:

| File path | Lines |
| --- | --- |
${LONGEST}

---

## Maintenance markers

* **TODO / FIXME / HACK comments in \`src/\` TS/TSX**: ${TODO_COUNT}
* **Commits in the last 90 days**: ${COMMITS_WINDOW} (of ${TOTAL_COMMITS} total)
* **Bot-attributed commits**: ${BOT_COMMITS} (${BOT_DESC}; \`[bot]\` authors only — inline coding assistants leave no co-author tag)
EOF
}

if [ "$OUT" = "-" ]; then
  render
else
  mkdir -p "$(dirname "$OUT")"
  render > "$OUT"
  echo "Wrote $OUT" >&2
  printf 'src TS/TSX: %s files, %s LoC | tests: %s | TODOs: %s | longest: see file\n' \
    "$TS_COUNT" "$TS_LOC" "$TS_TEST_COUNT" "$TODO_COUNT" >&2
fi
